language: node_js
node_js:
- '0.10'
before_install:
- npm install coffee-script
before_script:
- "./node_modules/.bin/cake archive"
script:
- "./node_modules/.bin/cake test"
deploy:
  provider: releases
  api_key:
    secure: 0yzJucOYgtgVHKDJ0f2knmnygeo5BakxRdiIQkyckXkoJ1q0O8Uqs0Q+uM+lF2s+NIuFteeBegwGtV0uFVqHqfRea2BZvLTu3TiN4rDXMCYoWjJ9rGJ9QKUom1o9j/ZH1vVs3asEFjaIB4GNBQ1hXgLbLQufbpJLwVIvKSVmoPs=
  file: build/cURLCodeGenerator.zip
  skip_cleanup: true
  on:
    tags: true
    all_branches: true
    repo: luckymarmot/Paw-cURLCodeGenerator
